name: Development Workflow

on:
  push:
    branches:
      - development

jobs:
   lint-test:
    runs-on: ubuntu-latest
    steps:
       name: Execute lint & test from shared file
        uses: ./.github/workflows/common.yml

